name: fin_fit_app_mobile
description: "Finantial Fitness Application"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  sqflite: ^2.3.2
  path: ^1.9.0
  drift: ^2.19.1+1
  path_provider: ^2.0.0
  sqlite3: ^2.4.2
  material_symbols_icons: ^4.2744.0
  google_fonts: ^6.2.0 
  drift_flutter: ^0.2.0
  popup_menu: ^2.1.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_database: ^11.3.0
  provider: ^6.1.2
  material_buttonx: ^2.0.3
  chat_gpt_sdk: 3.1.4
  flutter_dotenv: ^5.0.2
  velocity_x: ^4.3.1
  firebase_core_platform_interface: ^5.4.0
  firebase_auth_mocks: ^0.14.1
  mock_exceptions: ^0.8.2
  dart_style: ^3.1.0
  source_gen: ^2.0.0

dependency_overrides:
  analyzer: 7.3.0
  intl: ^0.19.0

dev_dependencies:
  drift_dev: ^2.19.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.9
  mockito: ^5.4.5
  test: ^1.25.15
  sqlite3_flutter_libs: ^0.5.34
  flutter_svg_test: 1.0.3
  clock: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/ic_target_24.svg
    - assets/ic_arrow_circle_up_24.svg
    - assets/ic_arrow_circle_down_24.svg
