// Mocks generated by Mockito 5.4.5 from annotations
// in fin_fit_app_mobile/test/command/edit_transaction_command_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i10;

import 'package:fin_fit_app_mobile/helper/category_table_helper.dart' as _i3;
import 'package:fin_fit_app_mobile/helper/movement_table_helper.dart' as _i2;
import 'package:fin_fit_app_mobile/service/database.dart' as _i8;
import 'package:fin_fit_app_mobile/ui/transaction_page.dart' as _i4;
import 'package:flutter/foundation.dart' as _i6;
import 'package:flutter/material.dart' as _i5;
import 'package:flutter/services.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovementTableHelper_0 extends _i1.SmartFake
    implements _i2.MovementTableHelper {
  _FakeMovementTableHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryTableHelper_1 extends _i1.SmartFake
    implements _i3.CategoryTableHelper {
  _FakeCategoryTableHelper_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionPageStateful_2 extends _i1.SmartFake
    implements _i4.TransactionPageStateful {
  _FakeTransactionPageStateful_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeBuildContext_3 extends _i1.SmartFake implements _i5.BuildContext {
  _FakeBuildContext_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWidget_4 extends _i1.SmartFake implements _i5.Widget {
  _FakeWidget_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_5 extends _i1.SmartFake
    implements _i5.DiagnosticsNode {
  _FakeDiagnosticsNode_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({
    _i6.TextTreeConfiguration? parentConfiguration,
    _i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info,
  }) => super.toString();
}

class _FakeInheritedWidget_6 extends _i1.SmartFake
    implements _i5.InheritedWidget {
  _FakeInheritedWidget_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [TransactionPage].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionPage extends _i1.Mock implements _i4.TransactionPage {
  MockTransactionPage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get date =>
      (super.noSuchMethod(
            Invocation.getter(#date),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#date)),
          )
          as String);

  @override
  set date(String? _date) => super.noSuchMethod(
    Invocation.setter(#date, _date),
    returnValueForMissingStub: null,
  );

  @override
  _i2.MovementTableHelper get movementTableHelper =>
      (super.noSuchMethod(
            Invocation.getter(#movementTableHelper),
            returnValue: _FakeMovementTableHelper_0(
              this,
              Invocation.getter(#movementTableHelper),
            ),
          )
          as _i2.MovementTableHelper);

  @override
  set movementTableHelper(_i2.MovementTableHelper? _movementTableHelper) =>
      super.noSuchMethod(
        Invocation.setter(#movementTableHelper, _movementTableHelper),
        returnValueForMissingStub: null,
      );

  @override
  _i3.CategoryTableHelper get categoryTableHelper =>
      (super.noSuchMethod(
            Invocation.getter(#categoryTableHelper),
            returnValue: _FakeCategoryTableHelper_1(
              this,
              Invocation.getter(#categoryTableHelper),
            ),
          )
          as _i3.CategoryTableHelper);

  @override
  set categoryTableHelper(_i3.CategoryTableHelper? _categoryTableHelper) =>
      super.noSuchMethod(
        Invocation.setter(#categoryTableHelper, _categoryTableHelper),
        returnValueForMissingStub: null,
      );

  @override
  List<_i8.CategoryData> get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: <_i8.CategoryData>[],
          )
          as List<_i8.CategoryData>);

  @override
  set categories(List<_i8.CategoryData>? _categories) => super.noSuchMethod(
    Invocation.setter(#categories, _categories),
    returnValueForMissingStub: null,
  );

  @override
  List<_i5.Widget> get containers =>
      (super.noSuchMethod(
            Invocation.getter(#containers),
            returnValue: <_i5.Widget>[],
          )
          as List<_i5.Widget>);

  @override
  set containers(List<_i5.Widget>? _containers) => super.noSuchMethod(
    Invocation.setter(#containers, _containers),
    returnValueForMissingStub: null,
  );

  @override
  List<_i8.MovementData> get transactions =>
      (super.noSuchMethod(
            Invocation.getter(#transactions),
            returnValue: <_i8.MovementData>[],
          )
          as List<_i8.MovementData>);

  @override
  set transactions(List<_i8.MovementData>? _transactions) => super.noSuchMethod(
    Invocation.setter(#transactions, _transactions),
    returnValueForMissingStub: null,
  );

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  set title(String? _title) => super.noSuchMethod(
    Invocation.setter(#title, _title),
    returnValueForMissingStub: null,
  );

  @override
  String get actionButton =>
      (super.noSuchMethod(
            Invocation.getter(#actionButton),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#actionButton),
            ),
          )
          as String);

  @override
  set actionButton(String? _actionButton) => super.noSuchMethod(
    Invocation.setter(#actionButton, _actionButton),
    returnValueForMissingStub: null,
  );

  @override
  String get locale =>
      (super.noSuchMethod(
            Invocation.getter(#locale),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#locale),
            ),
          )
          as String);

  @override
  set locale(String? _locale) => super.noSuchMethod(
    Invocation.setter(#locale, _locale),
    returnValueForMissingStub: null,
  );

  @override
  List<bool> get isEntryOrExit =>
      (super.noSuchMethod(
            Invocation.getter(#isEntryOrExit),
            returnValue: <bool>[],
          )
          as List<bool>);

  @override
  set isEntryOrExit(List<bool>? _isEntryOrExit) => super.noSuchMethod(
    Invocation.setter(#isEntryOrExit, _isEntryOrExit),
    returnValueForMissingStub: null,
  );

  @override
  _i4.TransactionPageStateful get widget =>
      (super.noSuchMethod(
            Invocation.getter(#widget),
            returnValue: _FakeTransactionPageStateful_2(
              this,
              Invocation.getter(#widget),
            ),
          )
          as _i4.TransactionPageStateful);

  @override
  _i5.BuildContext get context =>
      (super.noSuchMethod(
            Invocation.getter(#context),
            returnValue: _FakeBuildContext_3(this, Invocation.getter(#context)),
          )
          as _i5.BuildContext);

  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);

  @override
  void initState() => super.noSuchMethod(
    Invocation.method(#initState, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Widget build(_i5.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#build, [context]),
            returnValue: _FakeWidget_4(
              this,
              Invocation.method(#build, [context]),
            ),
          )
          as _i5.Widget);

  @override
  void setTransactionDialogText(bool? isToAdd) => super.noSuchMethod(
    Invocation.method(#setTransactionDialogText, [isToAdd]),
    returnValueForMissingStub: null,
  );

  @override
  void setFields(_i8.MovementData? item) => super.noSuchMethod(
    Invocation.method(#setFields, [item]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Widget getInflowOrOutflowIcon(bool? isIncome) =>
      (super.noSuchMethod(
            Invocation.method(#getInflowOrOutflowIcon, [isIncome]),
            returnValue: _FakeWidget_4(
              this,
              Invocation.method(#getInflowOrOutflowIcon, [isIncome]),
            ),
          )
          as _i5.Widget);

  @override
  _i9.Future<void> showAddOrEditDialog(bool? isToAdd, int? id) =>
      (super.noSuchMethod(
            Invocation.method(#showAddOrEditDialog, [isToAdd, id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> showDeleteDialog(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#showDeleteDialog, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  String returnMonthAndYear(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#returnMonthAndYear, [date]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#returnMonthAndYear, [date]),
            ),
          )
          as String);

  @override
  void didUpdateWidget(_i4.TransactionPageStateful? oldWidget) =>
      super.noSuchMethod(
        Invocation.method(#didUpdateWidget, [oldWidget]),
        returnValueForMissingStub: null,
      );

  @override
  void reassemble() => super.noSuchMethod(
    Invocation.method(#reassemble, []),
    returnValueForMissingStub: null,
  );

  @override
  void setState(_i10.VoidCallback? fn) => super.noSuchMethod(
    Invocation.method(#setState, [fn]),
    returnValueForMissingStub: null,
  );

  @override
  void deactivate() => super.noSuchMethod(
    Invocation.method(#deactivate, []),
    returnValueForMissingStub: null,
  );

  @override
  void activate() => super.noSuchMethod(
    Invocation.method(#activate, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeDependencies() => super.noSuchMethod(
    Invocation.method(#didChangeDependencies, []),
    returnValueForMissingStub: null,
  );

  @override
  void debugFillProperties(_i11.DiagnosticPropertiesBuilder? properties) =>
      super.noSuchMethod(
        Invocation.method(#debugFillProperties, [properties]),
        returnValueForMissingStub: null,
      );

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();

  @override
  String toStringShort() =>
      (super.noSuchMethod(
            Invocation.method(#toStringShort, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#toStringShort, []),
            ),
          )
          as String);

  @override
  _i5.DiagnosticsNode toDiagnosticsNode({
    String? name,
    _i6.DiagnosticsTreeStyle? style,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toDiagnosticsNode, [], {
              #name: name,
              #style: style,
            }),
            returnValue: _FakeDiagnosticsNode_5(
              this,
              Invocation.method(#toDiagnosticsNode, [], {
                #name: name,
                #style: style,
              }),
            ),
          )
          as _i5.DiagnosticsNode);
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i5.BuildContext {
  MockBuildContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Widget get widget =>
      (super.noSuchMethod(
            Invocation.getter(#widget),
            returnValue: _FakeWidget_4(this, Invocation.getter(#widget)),
          )
          as _i5.Widget);

  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);

  @override
  bool get debugDoingBuild =>
      (super.noSuchMethod(
            Invocation.getter(#debugDoingBuild),
            returnValue: false,
          )
          as bool);

  @override
  _i5.InheritedWidget dependOnInheritedElement(
    _i5.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #dependOnInheritedElement,
              [ancestor],
              {#aspect: aspect},
            ),
            returnValue: _FakeInheritedWidget_6(
              this,
              Invocation.method(
                #dependOnInheritedElement,
                [ancestor],
                {#aspect: aspect},
              ),
            ),
          )
          as _i5.InheritedWidget);

  @override
  void visitAncestorElements(_i5.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(#visitAncestorElements, [visitor]),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i5.ElementVisitor? visitor) => super.noSuchMethod(
    Invocation.method(#visitChildElements, [visitor]),
    returnValueForMissingStub: null,
  );

  @override
  void dispatchNotification(_i5.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(#dispatchNotification, [notification]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.DiagnosticsNode describeElement(
    String? name, {
    _i6.DiagnosticsTreeStyle? style = _i6.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#describeElement, [name], {#style: style}),
            returnValue: _FakeDiagnosticsNode_5(
              this,
              Invocation.method(#describeElement, [name], {#style: style}),
            ),
          )
          as _i5.DiagnosticsNode);

  @override
  _i5.DiagnosticsNode describeWidget(
    String? name, {
    _i6.DiagnosticsTreeStyle? style = _i6.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#describeWidget, [name], {#style: style}),
            returnValue: _FakeDiagnosticsNode_5(
              this,
              Invocation.method(#describeWidget, [name], {#style: style}),
            ),
          )
          as _i5.DiagnosticsNode);

  @override
  List<_i5.DiagnosticsNode> describeMissingAncestor({
    required Type? expectedAncestorType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#describeMissingAncestor, [], {
              #expectedAncestorType: expectedAncestorType,
            }),
            returnValue: <_i5.DiagnosticsNode>[],
          )
          as List<_i5.DiagnosticsNode>);

  @override
  _i5.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#describeOwnershipChain, [name]),
            returnValue: _FakeDiagnosticsNode_5(
              this,
              Invocation.method(#describeOwnershipChain, [name]),
            ),
          )
          as _i5.DiagnosticsNode);
}
